// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideOverlay():Promise<void>;

export function OnWindowBlur():Promise<void>;

export function ShowOverlay():Promise<void>;
