// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideOverlay() {
  return window['go']['main']['App']['HideOverlay']();
}

export function OnWindowBlur() {
  return window['go']['main']['App']['OnWindowBlur']();
}

export function ShowOverlay() {
  return window['go']['main']['App']['ShowOverlay']();
}
